import dotenv from 'dotenv';

dotenv.config();

export const {
  CONTENTFUL_SPACE_ID,
  CONTENTFUL_MANAGEMENT_ACCESS_TOKEN,
  CONTENTFUL_DELIVERY_ACCESS_TOKEN,
  CONTENTFUL_PREVIEW_ACCESS_TOKEN,
  NODE_ENV,
  HOST,
  PORT,
  LOG_LEVEL,
} = process.env;
